apiVersion: v1
kind: Service
metadata:
  name: {{ include "ride-viewer-app.fullname" . }}-internal
  labels:
    {{- include "ride-viewer-app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.nlb.internal }}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ride-viewer-app.selectorLabels" . | nindent 4 }}
